[package]
name = "euclidian"
version = "0.1.0"
authors = ["Marcin GÃ³rny <marcin.gorny.94@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "extended_euclidian_algorithm"
path = "src/lib.rs"